/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dremio_sabot_op_project_FletcherFilterProjectOperator */

#ifndef _Included_com_dremio_sabot_op_project_FletcherFilterProjectOperator
#define _Included_com_dremio_sabot_op_project_FletcherFilterProjectOperator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dremio_sabot_op_project_FletcherFilterProjectOperator
 * Method:    doNativeFletcher
 * Signature: ([BI[J[J)D
 */
JNIEXPORT jdouble JNICALL Java_com_dremio_sabot_op_project_FletcherFilterProjectOperator_doNativeFletcher
  (JNIEnv *, jobject, jbyteArray, jint, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
