/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dremio_sabot_op_filter_FilterTemplateAccelerated */

#ifndef _Included_com_dremio_sabot_op_filter_FilterTemplateAccelerated
#define _Included_com_dremio_sabot_op_filter_FilterTemplateAccelerated
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dremio_sabot_op_filter_FilterTemplateAccelerated
 * Method:    doNativeEval
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_dremio_sabot_op_filter_FilterTemplateAccelerated_doNativeEval
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
