name: Test

on:
  push:
    branches:
    - develop
  pull_request:

env:
  ARROW_VERSION: '1.0.1'
  MAVEN_VERSION: 3.6.3

jobs:
  dremio_accelerated:
    name: Dremio accelerated
    runs-on: ubuntu-latest
    container: centos:7
    env:
      JAVA_HOME: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64"
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yum install -y epel-release
        yum install -y java-1.8.0-openjdk-devel-1.8.0.275.b01-0.el7_9 curl git rpm-build gcc-c++ make cmake3
    - name: Install Maven
      run: curl -L https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | tar xz --strip-components=1 -C /usr
    - name: Install Apache Arrow
      run: |
        yum install -y https://apache.bintray.com/arrow/centos/$(cut -d: -f5 /etc/system-release-cpe | cut -d. -f1)/apache-arrow-release-latest.rpm
        yum install -y arrow-devel-${ARROW_VERSION}-1.el7
    - name: Install native_lib
      run: |
        mkdir -p build
        cd build
        cmake3 ../native
        make -j
        make install
        cd ..
        rm -rf build
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package -DskipTests -Prpm
    - uses: actions/upload-artifact@v2
      with:
        name: dremio-rpm
        path: distribution/server/target/rpm/dremio-community/RPMS/noarch/*.rpm

  native_filter:
    name: Native filter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Apache Arrow
      run: |
        wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt-get install -y ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt-get update
        sudo apt-get install -y libarrow-dev=$ARROW_VERSION-1
    - name: Configure
      run: cmake native
    - name: Build
      run: make -j
    - name: Install
      run: sudo make install
